// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.2
// source: protos/service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WindSpeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Speed         float64                `protobuf:"fixed64,3,opt,name=speed,proto3" json:"speed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WindSpeedResponse) Reset() {
	*x = WindSpeedResponse{}
	mi := &file_protos_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WindSpeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindSpeedResponse) ProtoMessage() {}

func (x *WindSpeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindSpeedResponse.ProtoReflect.Descriptor instead.
func (*WindSpeedResponse) Descriptor() ([]byte, []int) {
	return file_protos_service_proto_rawDescGZIP(), []int{0}
}

func (x *WindSpeedResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *WindSpeedResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WindSpeedResponse) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

var File_protos_service_proto protoreflect.FileDescriptor

const file_protos_service_proto_rawDesc = "" +
	"\n" +
	"\x14protos/service.proto\x12\x06iot404\x1a\x1bgoogle/protobuf/empty.proto\"[\n" +
	"\x11WindSpeedResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05speed\x18\x03 \x01(\x01R\x05speed2K\n" +
	"\aESP8266\x12@\n" +
	"\twindspeed\x12\x16.google.protobuf.Empty\x1a\x19.iot404.WindSpeedResponse\"\x00B\x06Z\x04./pbb\x06proto3"

var (
	file_protos_service_proto_rawDescOnce sync.Once
	file_protos_service_proto_rawDescData []byte
)

func file_protos_service_proto_rawDescGZIP() []byte {
	file_protos_service_proto_rawDescOnce.Do(func() {
		file_protos_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_service_proto_rawDesc), len(file_protos_service_proto_rawDesc)))
	})
	return file_protos_service_proto_rawDescData
}

var file_protos_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_service_proto_goTypes = []any{
	(*WindSpeedResponse)(nil), // 0: iot404.WindSpeedResponse
	(*emptypb.Empty)(nil),     // 1: google.protobuf.Empty
}
var file_protos_service_proto_depIdxs = []int32{
	1, // 0: iot404.ESP8266.windspeed:input_type -> google.protobuf.Empty
	0, // 1: iot404.ESP8266.windspeed:output_type -> iot404.WindSpeedResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_service_proto_init() }
func file_protos_service_proto_init() {
	if File_protos_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_service_proto_rawDesc), len(file_protos_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_service_proto_goTypes,
		DependencyIndexes: file_protos_service_proto_depIdxs,
		MessageInfos:      file_protos_service_proto_msgTypes,
	}.Build()
	File_protos_service_proto = out.File
	file_protos_service_proto_goTypes = nil
	file_protos_service_proto_depIdxs = nil
}
