// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.2
// source: protos/service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ESP8266_Windspeed_FullMethodName = "/iot404.ESP8266/windspeed"
)

// ESP8266Client is the client API for ESP8266 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ESP8266Client interface {
	Windspeed(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*WindSpeedResponse, error)
}

type eSP8266Client struct {
	cc grpc.ClientConnInterface
}

func NewESP8266Client(cc grpc.ClientConnInterface) ESP8266Client {
	return &eSP8266Client{cc}
}

func (c *eSP8266Client) Windspeed(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*WindSpeedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WindSpeedResponse)
	err := c.cc.Invoke(ctx, ESP8266_Windspeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ESP8266Server is the server API for ESP8266 service.
// All implementations must embed UnimplementedESP8266Server
// for forward compatibility.
type ESP8266Server interface {
	Windspeed(context.Context, *emptypb.Empty) (*WindSpeedResponse, error)
	mustEmbedUnimplementedESP8266Server()
}

// UnimplementedESP8266Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedESP8266Server struct{}

func (UnimplementedESP8266Server) Windspeed(context.Context, *emptypb.Empty) (*WindSpeedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Windspeed not implemented")
}
func (UnimplementedESP8266Server) mustEmbedUnimplementedESP8266Server() {}
func (UnimplementedESP8266Server) testEmbeddedByValue()                 {}

// UnsafeESP8266Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ESP8266Server will
// result in compilation errors.
type UnsafeESP8266Server interface {
	mustEmbedUnimplementedESP8266Server()
}

func RegisterESP8266Server(s grpc.ServiceRegistrar, srv ESP8266Server) {
	// If the following call panics, it indicates UnimplementedESP8266Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ESP8266_ServiceDesc, srv)
}

func _ESP8266_Windspeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ESP8266Server).Windspeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ESP8266_Windspeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ESP8266Server).Windspeed(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ESP8266_ServiceDesc is the grpc.ServiceDesc for ESP8266 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ESP8266_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "iot404.ESP8266",
	HandlerType: (*ESP8266Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "windspeed",
			Handler:    _ESP8266_Windspeed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/service.proto",
}
