persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

# Слушаем порт 1883
listener 1883 0.0.0.0
# Разрешаем анонимный вход (для тестов, позже добавим пароли)
allow_anonymous true