CREATE TABLE IF NOT EXISTS wind_speed (
    id INT AUTO_INCREMENT PRIMARY KEY,
    voltage DOUBLE NOT NULL,
    speed DOUBLE NOT NULL,
    ts BIGINT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS temperature (
    id INT AUTO_INCREMENT PRIMARY KEY,
    val DOUBLE NOT NULL,
    ts BIGINT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS humidity (
    id INT AUTO_INCREMENT PRIMARY KEY,
    val DOUBLE NOT NULL,
    ts BIGINT UNSIGNED NOT NULL
);