CREATE TABLE IF NOT EXISTS wind_speed (
    id INT AUTO_INCREMENT PRIMARY KEY,
    voltage FLOAT NOT NULL,
    speed FLOAT NOT NULL,
    ts BIGINT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS temperature (
    id INT AUTO_INCREMENT PRIMARY KEY,
    val FLOAT NOT NULL,
    ts BIGINT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS humidity (
    id INT AUTO_INCREMENT PRIMARY KEY,
    val FLOAT NOT NULL,
    ts BIGINT UNSIGNED NOT NULL
);